/*
 * This source file was generated by the Gradle 'init' task
 */
package io.github.theflysong;

import java.nio.ByteBuffer;

import org.joml.Matrix4f;
import org.lwjgl.system.MemoryUtil;

import io.github.theflysong.client.gl.GLGpuMesh;
import io.github.theflysong.client.gl.GLMeshBuilder;
import io.github.theflysong.client.gl.GLMeshData;
import io.github.theflysong.client.gl.GLMgr;
import io.github.theflysong.client.gl.GLRenderItem;
import io.github.theflysong.client.gl.GLRenderer;
import io.github.theflysong.client.gl.GLShaders;
import io.github.theflysong.client.gl.GLVertexLayouts;
import io.github.theflysong.client.gl.Shader;
import io.github.theflysong.client.gl.Window;
import io.github.theflysong.client.sprite.Models;
import io.github.theflysong.client.sprite.Sprite;
import io.github.theflysong.client.sprite.Sprites;
import io.github.theflysong.data.ResLoc;
import io.github.theflysong.data.ResType;

import static org.lwjgl.opengl.GL11C.GL_BLEND;
import static org.lwjgl.opengl.GL11C.GL_ONE_MINUS_SRC_ALPHA;
import static org.lwjgl.opengl.GL11C.GL_SRC_ALPHA;
import static org.lwjgl.opengl.GL11C.GL_UNSIGNED_INT;
import static org.lwjgl.opengl.GL11C.glBlendFunc;
import static org.lwjgl.opengl.GL11C.glEnable;

public class App {
    private static final float WINDOW_WIDTH = 960.0f;
    private static final float WINDOW_HEIGHT = 540.0f;

    private static final class AppState {
        private Sprite sprite;
        private Shader shader;
        private GLGpuMesh mesh;
        private GLRenderer renderer;
        private GLRenderItem renderItem;
    }

    public static void main(String[] args) {
        AppState state = new AppState();

        new Window((int) WINDOW_WIDTH, (int) WINDOW_HEIGHT, "linklink - Gem3 Overlay Demo")
                .onInit(() -> init(state))
                .onRender(() -> render(state))
                .onCleanup(() -> cleanup(state))
                .run();
    }

    private static void init(AppState state) {
        GLVertexLayouts.LAYOUTS.onInitialization();
        Models.initialize();
        GLShaders.SHADERS.onInitialization();
        Sprites.initialize();

        glEnable(GL_BLEND);
        glBlendFunc(GL_SRC_ALPHA, GL_ONE_MINUS_SRC_ALPHA);

        state.sprite = Sprites.GEM3.get();
        state.shader = state.sprite.shader();

        state.mesh = state.sprite.model().createGpuMesh();

        state.renderer = new GLRenderer();
        state.renderItem = new GLRenderItem(state.mesh, state.shader);

        setupUniforms(state.shader);
    }

    private static void render(AppState state) {
        GLMgr.getInstance().binding(0, state.sprite.textureOrThrow("layer0").glId());
        GLMgr.getInstance().binding(1, state.sprite.textureOrThrow("overlay").glId());

        state.renderer.submit(state.renderItem);
        state.renderer.flush();
    }

    private static void cleanup(AppState state) {
        if (state.mesh != null) {
            state.mesh.close();
        }
        Sprites.closeAll();
        Models.closeAll();
        GLShaders.closeAll();
    }

    private static void setupUniforms(Shader shader) {
        // 采样器绑定到纹理单元 0/1。
        shader.getUniform("sam_texture").ifPresent(u -> u.set(0));
        shader.getUniform("sam_overlay").ifPresent(u -> u.set(1));

        // MC 钻石偏青蓝色调；乘到基础纹理上。
        shader.getUniform("v4_spriteColor")
                .ifPresent(u -> u.set(0.35f, 0.90f, 1.00f, 1.0f));

        // 设置intensity
        shader.getUniform("f_overlayIntensity")
                .ifPresent(u -> u.set(0.7f));

        Matrix4f model = new Matrix4f().identity();
        float aspect = WINDOW_WIDTH / WINDOW_HEIGHT;
        // 用正交投影修正宽高比，避免在非正方形窗口中被拉伸/压扁。
        Matrix4f projection = new Matrix4f().ortho(-aspect, aspect, -1.0f, 1.0f, -1.0f, 1.0f);
        shader.getUniform("m4_model").ifPresent(u -> u.set(model));
        shader.getUniform("m4_projection").ifPresent(u -> u.set(projection));
    }
}