/*
 * This source file was generated by the Gradle 'init' task
 */
package io.theflysong.github;

import io.theflysong.github.client.gl.Window;
import io.theflysong.github.data.ResLoc;
import io.theflysong.github.data.ResType;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        ResLoc testLoc = new ResLoc("matcher", ResType.TEXT, "test.txt");
        String text = io.theflysong.github.data.ResLoader.loadText(testLoc);
        System.out.println(text);

        Window window = new Window(1920, 1080, "JAVA A");
        window.run();
    }
}